version: '2'

services:

  frontend-campus-stats:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - campus-stats-network

  backend-campus-stats:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - campus-stats-network
    expose:
      - "5000"
  
networks:
  campus-stats-network:
    driver: bridge